create_clock -period 10 -name sys_clk [get_ports clk]
set_property PACKAGE_PIN N14 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN P6 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports start]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

set_property PACKAGE_PIN N9 [get_ports spi_cs]
set_property IOSTANDARD LVCMOS33 [get_ports id_ok]
set_property IOSTANDARD LVCMOS33 [get_ports spi_cs]
set_property IOSTANDARD LVCMOS33 [get_ports spi_miso]
set_property IOSTANDARD LVCMOS33 [get_ports spi_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports spi_sclk]
set_property PACKAGE_PIN M6 [get_ports spi_miso]
set_property PACKAGE_PIN P9 [get_ports spi_mosi]
set_property PACKAGE_PIN N6 [get_ports spi_sclk]
set_property PACKAGE_PIN L3 [get_ports start]
set_property PACKAGE_PIN K13 [get_ports id_ok]
